const platforms = [
    {
        id: 62,
        name: "Atari Jaguar",
        platform_logo_id: "pl7y",
    },
    {
        id: 477,
        name: "Panasonic Jungle",
        platform_logo_id: "plnp",
    },
    {
        id: 504,
        name: "Uzebox",
        platform_logo_id: "plor",
    },
    {
        id: 148,
        name: "AY-3-8607",
    },
    {
        id: 65,
        name: "Atari 8-bit",
        platform_logo_id: "plad",
    },
    {
        id: 128,
        name: "PC Engine SuperGrafx",
        platform_logo_id: "pla4",
    },
    {
        id: 89,
        name: "Microvision",
        platform_logo_id: "pl8q",
    },
    {
        id: 8,
        name: "PlayStation 2",
        platform_logo_id: "pl72",
    },
    {
        id: 6,
        name: "PC (Microsoft Windows)",
        platform_logo_id: "plim",
    },
    {
        id: 23,
        name: "Dreamcast",
        platform_logo_id: "pl7i",
    },
]
export const IGDB_genres = {
    2: "Point-and-click",
    4: "Fighting",
    5: "Shooter",
    7: "Music",
    8: "Platform",
    9: "Puzzle",
    10: "Racing",
    11: "Real Time Strategy (RTS)",
    12: "Role-playing (RPG)",
    13: "Simulator",
    14: "Sports",
    15: "Strategy",
    16: "Turn-based strategy",
    24: "Tactical",
    25: "Hack and slash/Beat 'em up",
    26: "Quiz/Trivia",
    30: "Pinball",
    31: "Adventure",
    32: "Indie",
    33: "Arcade",
    34: "Visual Novel",
    35: "Card & Board Game",
    36: "MOBA",
}
